@foreach($tab['fields'] as $field)
    @formgroup
    @switch($field['type'])
    @case('select')
        @formselect($field)
        @endformselect
        @break
    @case('select_multiple')
        @formselectmultiple($field)
        @endformselectmultiple
        @break
    @case('textarea')
        @formtextarea($field)
        @endformtextarea
        @break
    @case('editor')
        @formeditor($field)
        @endformeditor
        @break
    @case('checkbox')
        @formcheckbox($field)
        @endformcheckbox
        @break
    @case('media')
        @formmedia($field)
        @endformmedia
        @break
    @default
        @forminput($field)
        @endforminput
        @break
    @endswitch
    @endformgroup
@endforeach